#need REST client application in vs code

GET http://localhost:8000/products/ HTTP/1.1


###
GET http://localhost:8000/products/1/ HTTP/1.1

###
POST http://localhost:8000/products/ HTTP/1.1
#This tell the server hat format the data need be sent in the request body

Content-Type: application/json

{
	"name": "Television",
	"price": 300.00,
	"stock": 14,
	"description": "An amazing new TV"    
}

###
#This endpoint is to show a token from the user 
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"username" : "osva",
	"password" : "aarontorres3108"

}

###
GET http://localhost:8000/user-orders/ HTTP/1.1


###
GET http://localhost:8000/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg1MjYyOTY2LCJpYXQiOjE3ODUyNjI2NjYsImp0aSI6ImY3ZTAwZWFiMGZjNDQyNzE4MjRiNWFjNDQxMmRlNGUxIiwidXNlcl9pZCI6IjEifQ.gdcPC9RcW3sMDt2w4MNW_y2Gcms20DfCHF6W-lbmIUU


###
POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg1NTEwNzAwLCJpYXQiOjE3ODU1MTA0MDAsImp0aSI6IjIyYTg4NjliMzQ4MTRlOTFiM2MzMDAzZjJiZmQ0ZmExIiwidXNlcl9pZCI6IjEifQ.6CtLCp3RswEoSWaRE0SCh588cWVP0Wxm74YqNuEJvO8

{
	"status": "Pending",
	"user":2,
	"items": [
		{
			"product": 1,
			"quantity": 2
		},
		{
			"product": 2,
			"quantity": 1
		}
	]
}


###
GET http://localhost:8000/orders/ HTTP/1.1
